directories:
  output: release
  buildResources: build
appId: com.guihub.app
productName: GuiHub
icon: build/icon.ico
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
extraMetadata:
  main: electron/main.cjs
files: []
electronVersion: 43.1.1
